### ISSUE TITLE
Can you please explain how does it work?

### ISSUE THREAD

**Issue by anonym24** [harshpalan/CrashHelp#1]
I would like to understand how it works.

For example I don't really understand what FORCE_THRESHOLD means and why by default it is 10000? What does this value mean?

And what possible appropriate ranges?

Dash cam devices have G-Sensor to prevent video from auto deletion during some accidents. There are G-Force units being used and measured as m/s².

Would be really thankful for your answer.

**Comment by harshpalan** [comment]
![image](https://user-images.githubusercontent.com/10105238/109526799-f9f46480-7ad8-11eb-8d93-fb9e3c2eadc5.png)

This is checked here against the accelerometer values. I don't remember how we come up with that number. We did some testing and it was giving us the response we needed.
